version: "3.9"

services:
  db:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: testdb
    restart: always

  app:
    container_name: springboot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MARIADB_ADDRESS: mariadb
      MARIADB_USERNAME: root
      MARIADB_PASSWORD: root
    depends_on:
      - db
    restart: always
